#cloud-config

apt_update: true

mounts:
 - [ vda, /mnt, "ext4", "defaults", "0", "2" ]

packages:
 - jmeter
 - curl
 - jq

runcmd:
 - cp -a /mnt/public /root/.ssh/id_rsa.pub
 - cp -a /mnt/private /root/.ssh/id_rsa
 - ip=$(curl http://169.254.169.254/2009-04-04/meta-data/local-ipv4)
 - sed -i -re "s/.*$(hostname).*/$ip $(hostname)/" /etc/hosts
 - ip_master=$(curl -s http://169.254.169.254/openstack/latest/meta_data.json | jq .meta.master | sed s'/\"//g')
 - ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@$ip_master "sed -i -re 's/(remote_hosts=.*)/\1$ip,/' /usr/share/jmeter/bin/jmeter.properties"
 - jmeter-server -Djava.rmi.server.hostname=$ip
